uint64 id
# Normalized feature coordinates (with identity intrinsic matrix)
float64 u0 # horizontal coordinate in cam0
float64 v0 # vertical coordinate in cam0
float64 u1 # horizontal coordinate in cam0
float64 v1 # vertical coordinate in cam0
float64 u0_o # horizontal coordinate in cam0
float64 v0_o # vertical coordinate in cam0
float64 u1_o # horizontal coordinate in cam0
float64 v1_o # vertical coordinate in cam0
